-- db/schema.sql
-- Pre-computed travel-time store for Czechia (see docs/plans/2026-06-15-001-*).
-- Run once on the target self-hosted Postgres (PostGIS-capable). Idempotent.
--
-- Exposure model (KTD8): base tables live in the private `dist` schema, which is
-- NOT added to PostgREST's `db-schemas`. Only the `api` schema is exposed, and it
-- holds just the read function (db/rpc.sql). The browser therefore cannot page
-- the matrix via auto-generated table endpoints.
--
-- Role assumption: a PostgREST `anon` role (your `db-anon-role`) is the
-- anonymous identity. Adjust the role name below if yours differs.

begin;

-- PostGIS in its own schema, never public.
create schema if not exists extensions;
create extension if not exists postgis with schema extensions;

-- Private base-data schema (do NOT expose via PostgREST db-schemas).
create schema if not exists dist;

-- Exposed read-API schema (add ONLY this to PostgREST db-schemas).
create schema if not exists api;

-- Snapshot metadata. Exactly one row is active at a time; the live `dist.seed`
-- and `dist.matrix` always describe that active build (KTD7 consistency invariant).
create table if not exists dist.matrix_version (
  id                  integer generated by default as identity primary key,
  extract_date        date        not null,   -- Geofabrik extract replication date
  profile_version     text        not null,   -- OSRM version / profile build id
  seed_spacing_km     numeric     not null,   -- launch target: 5 (KTD10)
  seed_set_hash       text        not null,   -- hash of sorted (id, rounded geom) set (U2)
  expected_row_count  bigint,
  actual_row_count    bigint,
  previous_version_id integer references dist.matrix_version(id),
  active              boolean     not null default false,
  created_at          timestamptz not null default now()
);

-- At most one active snapshot.
create unique index if not exists matrix_version_one_active
  on dist.matrix_version (active) where active;

-- Fixed national seed grid. `id` is deterministic and geometry-derived (U2),
-- never a sequence. geography(Point,4326) keeps snap + radius in true meters (KTD3).
create table if not exists dist.seed (
  id   integer primary key,
  geom extensions.geography(Point, 4326) not null
);
create index if not exists seed_geom_gix on dist.seed using gist (geom);

-- All-pairs car-driving duration matrix. The PK IS the access path for "all
-- destinations from one origin" (KTD4). `seconds` is nullable:
--   null   = unreachable (retained row, KTD5)
--   absent = out-of-radius (never means unreachable)
create table if not exists dist.matrix (
  origin_seed_id integer not null,
  dest_seed_id   integer not null,
  seconds        integer,
  primary key (origin_seed_id, dest_seed_id)
);

-- Ensure the PostgREST anon role exists (no-op if it already does).
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
end
$$;

-- Defense-in-depth: RLS on, no anon policy -> anon reads nothing even if a base
-- table were ever accidentally exposed. Real access is only via api.cells_around.
alter table dist.seed           enable row level security;
alter table dist.matrix         enable row level security;
alter table dist.matrix_version enable row level security;

-- anon may resolve the api schema (for the RPC) but has no rights on dist.
grant usage on schema api to anon;
revoke all on all tables in schema dist from anon;

commit;
